pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                    git clone https://github.com/tomcoh5/CICD.git
                    cd flask_container_ci
                    python3 dockerimage.py

                    
                    
            }
        stage('Build') {
                    sh dockerfile.sh
                    docker run -d -p 5000:5000 myflask
                    sh test.sh
                    python3 tests.py
        }
    }
}
